name: Build on PR

on: 
  pull_request:
    branches: 
      - main

jobs: 
  build:
    name: Build the project
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with: 
          node_version: '20'

      - name: Install Dependencies
        run: yarn install

      - name: Generate Prisma Client
        run: yarn run db:generate

      - name: Run Build
        run: yarn run build  